version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - user_data:/var/lib/postgresql/data
    networks:
      - appnet

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: users_db
      DB_USER: user
      DB_PASS: password
    depends_on:
      - db
    networks:
      - appnet
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - appnet
    restart: on-failure

volumes:
  user_data:

networks:
  appnet:
